---
- hosts: all
  become: true
  tasks:

   - name: Install base packages
     apt:
       state: present
       name: ['python3-pip','git']
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


   - name: upgrade/patch the server
     apt: upgrade=yes update_cache=yes
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


   - name: Install Pip dependencies as vagrant user
     become: true
     become_user: vagrant
     pip: requirements=/vagrant/requirements.txt
