---
- hosts: all
  become: true
  tasks:

   - name: Install packages
     apt:
       state: present
       name: ['python3-pip','git']


   - name: upgrade/patsh the server
     apt: upgrade=yes update_cache=yes

   - name: Install Pip dependencies
     pip: requirements=/vagrant/requirements.txt
