---
- hosts: all
  become: true
  tasks:

   - name: Install packages
     apt:
       state: present
       name: ['python3-pip','git']

    - name: Install Pip dependencies
      pip: requirements=/vagrant/requirements.txt
