# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.synced_folder '.', '/vagrant'

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2024"
  end 

  #config.vm.synced_folder '.', '/vagrant', nfs: true

  config.vm.define "myvm" do |myvm|
      myvm.vm.host_name = "myvm"

      #
      # bootstrap the VM with just the basic packages
      #
      myvm.vm.provision "shell", inline: <<-SHELL
       yum -y update
       #
       # rocky/centos seem to need some extra bits and an upgrade for pip
       # 
       yum install -y python3 python3-setuptools
       pip3 install --upgrade pip 
       pip3 install setuptools-rust
      SHELL

      #
      # now use ansible to finish the build
      #
      myvm.vm.provision "ansible" do |ansible|
          ansible.playbook = "build.yml"
      end
  end
end

